### ISSUE TITLE
Where can I get the configure file generate-mirrorlist-cache.cfg

### ISSUE THREAD

**Issue by awsome0305** [adrianreber/mirrorlist-server#122]
Hello,

there is no such binary (generate-mirrorlist-cache) or config file (generate-mirrorlist-cache.cfg).
Are you sure this is the right repository?

**Comment by adrianreber** [comment]
Have a look at Fedora's configuration file: https://pagure.io/fedora-infra/ansible/blob/main/f/roles/mirrormanager/backend/templates/generate-mirrorlist-cache.cfg

Binary: `cargo build` or `cargo build --release`.

**Comment by awsome0305** [comment]
Thanks.
