### ISSUE TITLE
Some lacking file errors

### ISSUE THREAD

**Issue by awsome0305** [adrianreber/mirrorlist-server#123]
Hi,

When I use command "mirrorlist-server", there are some lacking file errors.

How can I got "/var/lib/mirrormanager/i2_netblocks.txt" and "/var/lib/mirrormanager/global_netblocks.txt"

**Comment by awsome0305** [comment]
I have found the command in file "backend.corn".This is no longer a problem.

**Comment by adrianreber** [comment]
Yes, the scripts to create these files are here: https://github.com/fedora-infra/mirrormanager2/tree/master/utility
