### ISSUE TITLE
Releases on github

### ISSUE THREAD

**Issue by ignatenkobrain** [adrianreber/mirrorlist-server#2]
Hello @adrianreber, is there any reason you don't push git tags when releasing new version? It would be cool if you could do that.

Also, as for the versioning, would be nice to use `0.0.2` as version sinve it is still kinda experimental if I understand. Or, rather, follow semver better (I would expect with latest commits to have 1.0.1 version, rather than 2.0.0).

**Comment by adrianreber** [comment]
I had it tagged locally but forgot to push the tag. Thanks for the reminder.

Experimental? Hmm. Fedora has completely switched to this implementation. So the only possible user is using it 😉

If Rust (or Cargo) would not force to use three numbers for the version I would have just used a single number. Not convinced there is much value in incrementing only the first or last part of a version number. Especially for a leaf package like this.

As I understand it, the tagging was the most important part which I hopefully pushed now. Thanks for the reminder. Closing this.

**Comment by ignatenkobrain** [comment]
@adrianreber fair enough, thanks! :)
