### ISSUE TITLE
how to run mirrorlist-server correctly 

### ISSUE THREAD

**Issue by chenzeng765** [adrianreber/mirrorlist-server#241]
Since *mirrorlist-server* retrieves the repo information from the cache file generated by *generate-mirrorlist-cache*, then *mirrorlist-server* can't get the newest repo information stored in the database which will leads to the yum client fails by the reason, such as "checksum unmatched repomd.xml". Why not the *mirrorlist-server*  retrieve the repo information from database directly? Can you introduce how to run *mirrorlist-server* correctly which can get the newest repo information from database. Thanks very much.

**Comment by adrianreber** [comment]
Currently the main use case is for Fedora. There are about 70,000,000 requests per day from about 20 mirrorlist servers located all over the world. It would be really slow if every of those 70,000,000 requests would need access to the database.

For Fedora we created the cache files once an hour and copy it to all of the over 20 mirrorlist servers. This way each mirrorlist server does not need to do SQL queries directly, but can just load the data from local memory. That is much more efficient for Fedora's setup than talking directly to a database.

**Comment by chenzeng765** [comment]
Thanks very much for your explanation.  Another question is it seems that the mirrorlist-server doesn't reload the cache file again when the new cache file arrived. How do you make mirrorlist-server use the new cached data? Does restart mirrorlist-server  directly? If it is , why not use hot loading?

**Comment by adrianreber** [comment]
> Thanks very much for your explanation. Another question is it seems that the mirrorlist-server doesn't reload the cache > file again when the new cache file arrived. How do you make mirrorlist-server use the new cached data?

We have a scripts in Fedora and RPM Fusion which reload the mirrorlist-server process if new data has arrived:

 * https://pagure.io/fedora-infra/ansible/blob/main/f/roles/mirrormanager/mirrorlist_proxy/files/restart-mirrorlist-processes
 * https://github.com/rpmfusion-infra/ansible-rpmfusion/blob/master/roles/mirrormanager/mirrorlist-server/files/restart-mirrorlist-containers

> If it is , why not use hot loading?

We used to have code to automatically reload the data, but over time we changed to the current setup. No real reason. It works reliably with the current setup.
