### ISSUE TITLE
Upgrade hyper dependency to 0.13.x

### ISSUE THREAD

**Issue by ignatenkobrain** [adrianreber/mirrorlist-server#3]
Would be much appreciated.

Also you can set up @dependabot to send you PRs for dependencies update.

**Comment by adrianreber** [comment]
Thanks for letting me know. What does that mean for the release number? 2.0.1?

I need to figure out how dependabot works, but I will set it up.

Thanks for the Fedora RPM works flawlessly in Fedora Infrastructure production and serves over 30 million requests per day.

**Comment by ignatenkobrain** [comment]
> Thanks for letting me know. What does that mean for the release number? 2.0.1?

This is purely up to you. Since you don't provide any API for the Rust (aka library), you can name it 2.1.0 or 2.0.1, up to you :) I'd call it 2.1.0.

**Comment by adrianreber** [comment]
All dependabot changes have been merged and 2.1.0 has been released. Thanks for your help keeping this up to date.
